# Generated by Django 4.0.2 on 2022-02-27 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pages',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='mainapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=400)),
                ('imageurl', models.ImageField(upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Text', to='mainapp.artcategory')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='mainapp.user')),
            ],
        ),
    ]
