# Generated by Django 4.0.2 on 2022-02-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_product_pages_notification_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(max_length=12),
        ),
    ]
