# Generated by Django 4.0.2 on 2022-03-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_product_description_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accesstoken',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refreshtoken',
        ),
    ]
