# Generated by Django 4.0.2 on 2022-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_notification_designer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.IntegerField()),
                ('PartyA', models.IntegerField()),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
