# Generated by Django 4.0.2 on 2022-03-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_mpesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesa',
            name='PartyA',
        ),
    ]
