# Generated by Django 4.0.2 on 2022-03-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_mpesa_partya'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mpesa',
        ),
    ]
