# Generated by Django 4.0.2 on 2022-03-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
