# Generated by Django 4.0.2 on 2022-03-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
