# Generated by Django 4.0.2 on 2022-03-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='imageurl',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageurl',
            field=models.URLField(),
        ),
    ]
