# Generated by Django 4.0.2 on 2022-03-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_cart_imageurl_alter_product_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='designer',
            new_name='designer_name',
        ),
        migrations.AddField(
            model_name='product',
            name='designer_id',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
