# Generated by Django 4.0.2 on 2022-03-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_rename_designer_product_designer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='designer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='designer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
