# Generated by Django 4.0.2 on 2022-04-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_remove_mpesa_amount_remove_notification_designer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesa',
            name='productid',
        ),
        migrations.AddField(
            model_name='mpesa',
            name='Amount',
            field=models.IntegerField(null=True),
        ),
    ]
